# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packet.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cpacket.proto\"(\n\x08PacketId\x12\x0b\n\x03seq\x18\x01 \x01(\x03\x12\x0f\n\x07\x61ttempt\x18\x02 \x01(\x04\"<\n\x11PlainPacketHeader\x12\x0e\n\x06is_syn\x18\x01 \x01(\x08\x12\x17\n\x04\x61\x63ks\x18\x02 \x03(\x0b\x32\t.PacketId\"K\n\nPacketBody\x12\x15\n\x02id\x18\x01 \x01(\x0b\x32\t.PacketId\x12\x10\n\x07payload\x18\xe8\x07 \x01(\x0c\x12\x14\n\x0bobfuscation\x18\xe9\x07 \x01(\x0c\"M\n\x0bPlainPacket\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.PlainPacketHeader\x12\x1a\n\x04\x62ody\x18\xe8\x07 \x01(\x0b\x32\x0b.PacketBody\"d\n\x12SecurePacketHeader\x12\x0e\n\x06is_syn\x18\x01 \x01(\x08\x12\x17\n\x04\x61\x63ks\x18\x02 \x03(\x0b\x32\t.PacketId\x12\x0e\n\x06\x64h_pub\x18g \x01(\x0c\x12\t\n\x01n\x18h \x01(\x04\x12\n\n\x02pn\x18i \x01(\x03\"B\n\x0cSecurePacket\x12#\n\x06header\x18\x01 \x01(\x0b\x32\x13.SecurePacketHeader\x12\r\n\x04\x62ody\x18\xe8\x07 \x01(\x0c\x62\x06proto3')
)




_PACKETID = _descriptor.Descriptor(
  name='PacketId',
  full_name='PacketId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='PacketId.seq', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attempt', full_name='PacketId.attempt', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=56,
)


_PLAINPACKETHEADER = _descriptor.Descriptor(
  name='PlainPacketHeader',
  full_name='PlainPacketHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_syn', full_name='PlainPacketHeader.is_syn', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acks', full_name='PlainPacketHeader.acks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=118,
)


_PACKETBODY = _descriptor.Descriptor(
  name='PacketBody',
  full_name='PacketBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PacketBody.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='PacketBody.payload', index=1,
      number=1000, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obfuscation', full_name='PacketBody.obfuscation', index=2,
      number=1001, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=195,
)


_PLAINPACKET = _descriptor.Descriptor(
  name='PlainPacket',
  full_name='PlainPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='PlainPacket.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='PlainPacket.body', index=1,
      number=1000, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=274,
)


_SECUREPACKETHEADER = _descriptor.Descriptor(
  name='SecurePacketHeader',
  full_name='SecurePacketHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_syn', full_name='SecurePacketHeader.is_syn', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acks', full_name='SecurePacketHeader.acks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dh_pub', full_name='SecurePacketHeader.dh_pub', index=2,
      number=103, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n', full_name='SecurePacketHeader.n', index=3,
      number=104, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pn', full_name='SecurePacketHeader.pn', index=4,
      number=105, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=376,
)


_SECUREPACKET = _descriptor.Descriptor(
  name='SecurePacket',
  full_name='SecurePacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='SecurePacket.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='SecurePacket.body', index=1,
      number=1000, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=444,
)

_PLAINPACKETHEADER.fields_by_name['acks'].message_type = _PACKETID
_PACKETBODY.fields_by_name['id'].message_type = _PACKETID
_PLAINPACKET.fields_by_name['header'].message_type = _PLAINPACKETHEADER
_PLAINPACKET.fields_by_name['body'].message_type = _PACKETBODY
_SECUREPACKETHEADER.fields_by_name['acks'].message_type = _PACKETID
_SECUREPACKET.fields_by_name['header'].message_type = _SECUREPACKETHEADER
DESCRIPTOR.message_types_by_name['PacketId'] = _PACKETID
DESCRIPTOR.message_types_by_name['PlainPacketHeader'] = _PLAINPACKETHEADER
DESCRIPTOR.message_types_by_name['PacketBody'] = _PACKETBODY
DESCRIPTOR.message_types_by_name['PlainPacket'] = _PLAINPACKET
DESCRIPTOR.message_types_by_name['SecurePacketHeader'] = _SECUREPACKETHEADER
DESCRIPTOR.message_types_by_name['SecurePacket'] = _SECUREPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketId = _reflection.GeneratedProtocolMessageType('PacketId', (_message.Message,), dict(
  DESCRIPTOR = _PACKETID,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:PacketId)
  ))
_sym_db.RegisterMessage(PacketId)

PlainPacketHeader = _reflection.GeneratedProtocolMessageType('PlainPacketHeader', (_message.Message,), dict(
  DESCRIPTOR = _PLAINPACKETHEADER,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:PlainPacketHeader)
  ))
_sym_db.RegisterMessage(PlainPacketHeader)

PacketBody = _reflection.GeneratedProtocolMessageType('PacketBody', (_message.Message,), dict(
  DESCRIPTOR = _PACKETBODY,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:PacketBody)
  ))
_sym_db.RegisterMessage(PacketBody)

PlainPacket = _reflection.GeneratedProtocolMessageType('PlainPacket', (_message.Message,), dict(
  DESCRIPTOR = _PLAINPACKET,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:PlainPacket)
  ))
_sym_db.RegisterMessage(PlainPacket)

SecurePacketHeader = _reflection.GeneratedProtocolMessageType('SecurePacketHeader', (_message.Message,), dict(
  DESCRIPTOR = _SECUREPACKETHEADER,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:SecurePacketHeader)
  ))
_sym_db.RegisterMessage(SecurePacketHeader)

SecurePacket = _reflection.GeneratedProtocolMessageType('SecurePacket', (_message.Message,), dict(
  DESCRIPTOR = _SECUREPACKET,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:SecurePacket)
  ))
_sym_db.RegisterMessage(SecurePacket)


# @@protoc_insertion_point(module_scope)
